fix(connection): Catch CancelledError in CDPSession.send()
I use Pyppeteer in production for a few weeks and I notice a few exceptions like
this:
```
Task exception was never retrieved
future: <Task finished name='Task-36' coro=<Connection._recv_loop() done,
defined at .local/lib/python3.9/site-packages/pyppeteer/connection.py:53>
exception=InvalidStateError('invalid state')>
Traceback (most recent call last):
  File "/home/hoel/.local/lib/python3.9/site-packages/pyppeteer/connection.py", line 61, in _recv_loop
    await self._on_message(resp)
  File "/home/hoel/.local/lib/python3.9/site-packages/pyppeteer/connection.py", line 143, in _on_message
    self._on_query(msg)
  File "/home/hoel/.local/lib/python3.9/site-packages/pyppeteer/connection.py", line 127, in _on_query
    session._on_closed()
  File "/home/hoel/.local/lib/python3.9/site-packages/pyppeteer/connection.py", line 302, in _on_closed
    cb.set_exception(_rewriteError(
asyncio.exceptions.InvalidStateError: invalid state
```

My Python code goes like this:
```py
async def generate_a_pdf():
    try:
        browser = await pyppeteer.connect(browserURL='http://localhost:9222')
        tab = await browser.newPage()
        await tab.setContent()
        await tab.pdf()
    finally:
        await tab.close()
        await browser.disconnect()

async def my_web_server():
    task = asyncio.create_task(generate_a_pdf())

    # Wait for 1 second
    await asyncio.sleep(1)

    # Now some random error occurs, e.g. a HTTP client disconnection.
    # Simulate it with:
    task.cancel()

    try:
        await task
    except asyncio.CancelledError:
        pass

asyncio.run(my_web_server())
```
After looking into Pyppeteer I understand that the `callback` created by the
`CDPSession.send()` function is not cleaned in case of a cancellation
of the future `CDPSession.send()` by the asyncio Python `loop` creator.
Thus, after `await browser.disconnect()`, when Chromium sent its
`Target.detachedFromTarget` message, Pyppeteer finds this unanswered callback
and tries to return an exception on it.
Raising the callback exception failed on a
`asyncio.exceptions.InvalidStateError` because the `CDPSession.send()` future
have been cancelled.

To fix it I propose to shield `CDPSession.send()` against being cancelled, and
to catch the `CancelledError` exception the time needed to complete
`CDPSession.send()`.
Another solution could be to catch `CancelledError` and unregister
`CDPSession.send()` callback, but it sounds dangerous to me.

I suppose the upstream Puppeteer code doesn't have this issue because Node.js
coroutines can't be cancelled when running, but in Python, you need to deal
with the cancellation of future objects.